name: internal tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, master, development ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --config golangci.yaml ./...

  e2e-tests:
    runs-on: ubuntu-latest
    needs: golangci-lint
    env:
      RUN_ADDRESS: localhost:8080
      DB_DSN_HOST: localhost
      DB_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
      AUTH_SECRET: secret
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Make accrual binary executable
        run: |
          if [ -f cmd/accrual/accrual_linux_amd64 ]; then
            chmod +x cmd/accrual/accrual_linux_amd64
          fi

      - name: Run e2e tests
        shell: bash
        run: |
          make e2e

      - name: Show logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            .tmp/**
            .tmp/server.log
            .tmp/accrual.log
          if-no-files-found: ignore
